# Generated by Django 5.2.7 on 2025-10-24 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_devicetype_description_alter_devicetype_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iotdata',
            options={'ordering': ['-created_at'], 'verbose_name': 'IoT Data', 'verbose_name_plural': 'IoT Data'},
        ),
    ]
